# A sample Gemfile
source "https://rubygems.org"

ruby '2.1.5'

gem 'sinatra', require: 'sinatra/base'
gem 'erubis'
gem 'rake'
gem 'unicorn'
gem 'dotenv'

# DB
gem 'sequel'
gem 'sinatra-sequel'
gem 'mysql2'

group :development do
  # If you want to use Guard, uncomment these lines
  #gem 'guard'
  #gem 'compass'
  #gem 'sass', "~> 3.2.1"
  #gem 'guard-sass', "~> 1.0.0"
  #gem 'guard-jslint-on-rails'
  #gem 'guard-jammit'
  #gem 'guard-shell'
  #gem 'guard-coffeescript'
  #gem 'rb-fsevent', :require => false
  gem 'awesome_print'
  gem 'bones'
end
