# A sample Gemfile
source "https://rubygems.org"

ruby '2.1.5'

gem 'sinatra', require: 'sinatra/base'
gem 'erubis'
gem 'rake'
gem 'unicorn'
gem 'dotenv'

# DB
gem 'sequel'
gem 'sinatra-sequel'
gem 'mysql2'

group :development do
  gem 'awesome_print'
  gem 'bones'
end
